name: Secure CI/CD Pipeline

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_call:
    inputs:
      trivy_report_path:
        type: string
        description: 'Path to Trivy report file'
        required: false
        default: 'trivy-report.sarif'
      phpstan_report_path:
        type: string
        description: 'Path to PHPStan report file'
        required: false
        default: 'phpstan-report.sarif'
  workflow_dispatch:

jobs:
  trivy_scan:
    runs-on: ubuntu-latest
    name: Trivy SCA Scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Trivy SCA Scan
        uses: aquasecurity/trivy-action@v0.6.0
        with:
          format: "json"
          exit-code: "0,1,2"
          vuln-type: "os,library,application"
          ignore-unfixed: "true"
        id: trivy
      - name: Upload Trivy Report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ env.TRIVY_REPORT_PATH }}

  phpstan_scan:
    runs-on: ubuntu-latest
    name: PHPStan SAST Scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: PHPStan SAST Scan
        uses: ondrejmirtes/phpstan-ga-action@v2.0
        with:
          level: 5
      - name: Upload PHPStan Report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ env.PHPSTAN_REPORT_PATH }}

  phpcs_scan:
    runs-on: ubuntu-latest
    name: PHP CodeSniffer Quality Check
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: PHP CodeSniffer Quality Check
        uses: drupalcodequality/phpcodesniffer-ga-action@v3.3.1
        with:
          standard: PSR12
      - name: Upload PHP CodeSniffer Report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ env.PHPCS_REPORT_PATH }}

  upload_reports:
    runs-on: ubuntu-latest
    name: Upload Reports
    needs: [trivy_scan, phpstan_scan, phpcs_scan]
    steps:
      - name: Combine Reports
        run: |
          trivy_report_path=$GITHUB_WORKSPACE/${{ env.TRIVY_REPORT_PATH }}
          phpstan_report_path=$GITHUB_WORKSPACE/${{ env.PHPSTAN_REPORT_PATH }}
          phpcs_report_path=$GITHUB_WORKSPACE/${{ env.PHPCS_REPORT_PATH }}
          echo "{\"$schema\": \"https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.5.json\", \"version\": \"2.1.0\", \"runs\": [$(cat $trivy_report_path),$'\n',$(cat $phpstan_report_path),$'\n',$(cat $phpcs_report_path)]}" > combined.s
