name: Secure CI/CD Pipeline

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TRIVY_REPORT_PATH: 'trivy-report.sarif'
  PSALM_REPORT_PATH: 'psalm-report.sarif'
  TRUFFLEHOG_REPORT_PATH: 'trufflehog-report.sarif'

on:
  workflow_call:
    inputs:
      trivy_report_path:
        type: string
        description: 'Path to Trivy report file'
        required: false
        default: 'trivy-report.sarif'
      psalm_report_path:
        type: string
        description: 'Path to Psalm report file'
        required: false
        default: 'psalm-report.sarif'
        
  workflow_dispatch:

jobs:
  trivy_scan:
    runs-on: ubuntu-latest
    name: Trivy SCA Scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Trivy SCA Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'sarif'
          output: ${{ env.TRIVY_REPORT_PATH }}
        id: trivy
        
      - name: debug
        run: |
          ls -alh
      - name: Change permission of report to runner:docker
        run: | 
          sudo chown runner:docker $TRIVY_REPORT_PATH
          ls -alh $TRIVY_REPORT_PATH
        
      - name: Upload Trivy Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ env.TRIVY_REPORT_PATH }}
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Trivy SCA Report
          path: ${{ env.TRIVY_REPORT_PATH }}
          retention-days: 30
          
  psalm_scan:
    runs-on: ubuntu-latest
    name: Psalm PHP SAST Scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Psalm Security Scan
        uses: docker://ghcr.io/psalm/psalm-security-scan
        with:
          security_analysis: true
          report_file: ${{ env.PSALM_REPORT_PATH }}
        
      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ env.PSALM_REPORT_PATH }}
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Psalm SAST Report
          path: ${{ env.PSALM_REPORT_PATH }}
          retention-days: 30
          
  trufflehog_scanning:
    runs-on: ubuntu-latest
    name: TruffleHog Secrets Scanning
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: trufflehog-actions-scan
      uses: edplato/trufflehog-actions-scan@master
      with:
          scanArguments: "--max_depth=50 --entropy=False"          
        
  phpcs_scan:
    runs-on: ubuntu-latest
    name: PHP CodeSniffer (Code Quality - Not security)
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: php-codesniffer
        uses: pipeline-components/php-codesniffer@v0.12.3
        with:
          standard: PSR2
        id: phpcs
        continue-on-error: true
